version: '3.8'

services:
  listenbrainz-integration:
    build: .
    container_name: listenbrainz-integration
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    environment:
      # ListenBrainz Configuration
      - LB_USER=your_listenbrainz_username
      - METABRAINZ_TOKEN=your_metabrainz_token
      
      # MusicBrainz Configuration  
      - MB_MIRROR=musicbrainz.org  # or your local mirror like 192.168.1.200:5000
      
      # Plex Configuration
      - PLEX_BASE_URL=http://your-plex-server:32400
      - PLEX_TOKEN=your_plex_token
      
      # Application Configuration
      - HTTP_PORT=8000
      - NULLONLY=FALSE  # Set to TRUE to only include unlistened tracks
      - PLEX_DAYS_FILTER=14  # Days to look back for Plex playlists
      - LIDARR_UPDATE_INTERVAL=86400  # Lidarr update interval in seconds (24 hours)
      - PLEX_UPDATE_INTERVAL=86400    # Plex update interval in seconds (24 hours)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
