version: '3.8'

services:
  lb-lidarr-plex:
    image: ghcr.io/devianteng/lb-lidarr-plex:latest
    networks:
      - lb-lidarr-plex-network
    ports:
      - "8000:8000"
    volumes:
      - lb-config:/config
    environment:
      # ListenBrainz Configuration
      - LB_USER=your_listenbrainz_username
      - METABRAINZ_TOKEN=your_metabrainz_token

      # MusicBrainz Configuration
      - MB_MIRROR=musicbrainz.org  # or your local mirror like 192.168.1.200:5000

      # Plex Configuration
      - PLEX_BASE_URL=http://your-plex-server:32400
      - PLEX_TOKEN=your_plex_token

      # Application Configuration
      - HTTP_PORT=8000
      - NULLONLY=FALSE
      - PLEX_DAYS_FILTER=14
      - LIDARR_UPDATE_INTERVAL=86400
      - PLEX_UPDATE_INTERVAL=86400
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.id

networks:
  lb-lidarr-plex-network:
    driver: overlay
    attachable: true

volumes:
  lb-config:
    driver: local
